#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

-- Crear usuario de la aplicación
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_DB_USER}') THEN
      CREATE ROLE "${APP_DB_USER}" WITH LOGIN PASSWORD '${APP_DB_PASSWORD}';
   END IF;
END
\$\$;

-- Permitir conexión
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";

-- Acceso al schema
GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";

-- Permisos sobre tablas existentes
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO "${APP_DB_USER}";

-- Permisos para tablas futuras
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_DB_USER}";

-- Permisos sobre secuencias (importante si usas SERIAL / IDENTITY)
GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO "${APP_DB_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO "${APP_DB_USER}";

-- Permisos sobre funciones
GRANT EXECUTE
ON ALL FUNCTIONS IN SCHEMA public
TO "${APP_DB_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO "${APP_DB_USER}";

EOSQL
